CREATE TABLE [dbo].[tblAdressDICCountry]
(
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Country] [varchar](200) NOT NULL
 CONSTRAINT [PK_tblAdressDICCountry] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]