CREATE TABLE [dbo].[tblAdressBOBStreet](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[id_City] [int] NOT NULL,
	[Name] [varchar](200) NOT NULL,

CONSTRAINT [FK_tblAdressBOBStreet_tblCityBOBCity] FOREIGN KEY([id_City]) REFERENCES [dbo].[tblCityBOBCity] ([id]),
 CONSTRAINT [PK_tblAdressBOBStreet] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]