//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TM_CarWash.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCarWashLinks
    {
        public tblCarWashLinks()
        {
            this.tblUsers2CarWashList = new HashSet<tblUsers2CarWashList>();
        }
    
        public int Id { get; set; }
        public System.Guid ExternalLink { get; set; }
        public Nullable<short> Rate { get; set; }
    
        public virtual ICollection<tblUsers2CarWashList> tblUsers2CarWashList { get; set; }
    }
}
