//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TM_CarWash.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsers2CarWashList
    {
        public int Id { get; set; }
        public int id_User { get; set; }
        public int id_CarWashLink { get; set; }
        public int id_Users2CarWashListType { get; set; }
    
        public virtual tblCarWashLinks tblCarWashLinks { get; set; }
        public virtual tblUsers tblUsers { get; set; }
        public virtual tblUsers2CarWashListType tblUsers2CarWashListType { get; set; }
    }
}
