//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TM_CarWash.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TM_CarWashEFContext : DbContext
    {
        public TM_CarWashEFContext()
            : base("name=TM_CarWashEFContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCarWashLinks> tblCarWashLinks { get; set; }
        public virtual DbSet<tblUsers> tblUsers { get; set; }
        public virtual DbSet<tblUsers2CarWashList> tblUsers2CarWashList { get; set; }
        public virtual DbSet<tblUsers2CarWashListType> tblUsers2CarWashListType { get; set; }
    }
}
