//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TM_AdressSystem.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_Telemetry_AdressSystemEntities : DbContext
    {
        public DB_Telemetry_AdressSystemEntities()
            : base("name=DB_Telemetry_AdressSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAdressBOBPlace> tblAdressBOBPlace { get; set; }
        public virtual DbSet<tblAdressBOBRegions> tblAdressBOBRegions { get; set; }
        public virtual DbSet<tblAdressBOBSmallRegions> tblAdressBOBSmallRegions { get; set; }
        public virtual DbSet<tblAdressBOBStates> tblAdressBOBStates { get; set; }
        public virtual DbSet<tblAdressBOBStreet> tblAdressBOBStreet { get; set; }
        public virtual DbSet<tblAdressDICCountry> tblAdressDICCountry { get; set; }
        public virtual DbSet<tblCityBOBCity> tblCityBOBCity { get; set; }
    
        public virtual ObjectResult<spGetNearestCarWashsByRXRY_Result> spGetNearestCarWashsByRXRY(Nullable<int> userId, Nullable<decimal> lon, Nullable<decimal> lat, Nullable<decimal> rangeX, Nullable<decimal> rangeY, Nullable<int> maxItemsCount)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var lonParameter = lon.HasValue ?
                new ObjectParameter("Lon", lon) :
                new ObjectParameter("Lon", typeof(decimal));
    
            var latParameter = lat.HasValue ?
                new ObjectParameter("Lat", lat) :
                new ObjectParameter("Lat", typeof(decimal));
    
            var rangeXParameter = rangeX.HasValue ?
                new ObjectParameter("RangeX", rangeX) :
                new ObjectParameter("RangeX", typeof(decimal));
    
            var rangeYParameter = rangeY.HasValue ?
                new ObjectParameter("RangeY", rangeY) :
                new ObjectParameter("RangeY", typeof(decimal));
    
            var maxItemsCountParameter = maxItemsCount.HasValue ?
                new ObjectParameter("MaxItemsCount", maxItemsCount) :
                new ObjectParameter("MaxItemsCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetNearestCarWashsByRXRY_Result>("spGetNearestCarWashsByRXRY", userIdParameter, lonParameter, latParameter, rangeXParameter, rangeYParameter, maxItemsCountParameter);
        }
    
        public virtual ObjectResult<spGetNearestCarWashsByMaxRange_Result> spGetNearestCarWashsByMaxRange(Nullable<int> userId, Nullable<decimal> lon, Nullable<decimal> lat, Nullable<decimal> maxRange, Nullable<int> maxItemsCount)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var lonParameter = lon.HasValue ?
                new ObjectParameter("Lon", lon) :
                new ObjectParameter("Lon", typeof(decimal));
    
            var latParameter = lat.HasValue ?
                new ObjectParameter("Lat", lat) :
                new ObjectParameter("Lat", typeof(decimal));
    
            var maxRangeParameter = maxRange.HasValue ?
                new ObjectParameter("MaxRange", maxRange) :
                new ObjectParameter("MaxRange", typeof(decimal));
    
            var maxItemsCountParameter = maxItemsCount.HasValue ?
                new ObjectParameter("MaxItemsCount", maxItemsCount) :
                new ObjectParameter("MaxItemsCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetNearestCarWashsByMaxRange_Result>("spGetNearestCarWashsByMaxRange", userIdParameter, lonParameter, latParameter, maxRangeParameter, maxItemsCountParameter);
        }
    }
}
