//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TM_AdressSystem.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdressBOBStreet
    {
        public tblAdressBOBStreet()
        {
            this.tblAdressBOBPlace = new HashSet<tblAdressBOBPlace>();
        }
    
        public int id { get; set; }
        public int id_City { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<tblAdressBOBPlace> tblAdressBOBPlace { get; set; }
        public virtual tblCityBOBCity tblCityBOBCity { get; set; }
    }
}
