//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TM_AdressSystem.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdressBOBSmallRegions
    {
        public tblAdressBOBSmallRegions()
        {
            this.tblCityBOBCity = new HashSet<tblCityBOBCity>();
        }
    
        public int id { get; set; }
        public int id_State { get; set; }
        public string Name { get; set; }
    
        public virtual tblAdressBOBStates tblAdressBOBStates { get; set; }
        public virtual ICollection<tblCityBOBCity> tblCityBOBCity { get; set; }
    }
}
