//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TM_AdressSystem.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdressDICCountry
    {
        public tblAdressDICCountry()
        {
            this.tblAdressBOBRegions = new HashSet<tblAdressBOBRegions>();
        }
    
        public int id { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<tblAdressBOBRegions> tblAdressBOBRegions { get; set; }
    }
}
