//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TM_AdressSystem.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdressBOBRegions
    {
        public tblAdressBOBRegions()
        {
            this.tblAdressBOBStates = new HashSet<tblAdressBOBStates>();
        }
    
        public int id { get; set; }
        public int id_Country { get; set; }
        public string Name { get; set; }
    
        public virtual tblAdressDICCountry tblAdressDICCountry { get; set; }
        public virtual ICollection<tblAdressBOBStates> tblAdressBOBStates { get; set; }
    }
}
